= HubPress: A First Posting
:hp-tags: HubPress, blog, open source, GitHub, content management, CMS, publishing, writing, poetry

Oh, I see. 

The save icon does not appear unless you have a first-level heading as your title. 

Okay. 

I am an aging poetry major who -- having worked in technical writing and other fields over the course of a long & eclectic career -- has developed an insatiable curiosity about all aspects of Web publishing -- the many tools of this bitch goddess of a trade.

https://www.questia.com/library/745252/words-into-type-a-guide-in-the-preparation-of-manuscripts[Words Into Type].

An https://www.archlinux.org/[Arch Linux] man myself, I recently installed https://www.ampps.com[AMPPS] on the crappy Windows XP box at my place of internment and am reveling in the opportunity to auto-install -- count them -- 401 flavors of what in post-modernity we cannot help  calling content management. 

Content is what comes in McDonalds apple pies. Humans produce communication. But oh well. 

I have a separate http://linuxmint.com[Linux Mint] box to which I think I will try installing the AMPPS package after I back up my http folder to the Cloud.  

Eventually, what I want to do myself is figure out how to compile my http://dokuwiki.org[DocuWiki] book of hours and my http://datenstrom.se/yellow/[Yellow CMS] installation into https://www.staticgen.com/[static HTML that can also be pushed to GitHub]. 

One of these days I will figure it all out. In the meantime, many mercis beaucoups to Anthonny for this groovy innovation.